FROM gradle:7-jdk17-focal as build
WORKDIR /app
COPY . .
RUN gradle :client:build

FROM eclipse-temurin:17-jdk-focal as run
WORKDIR /app
COPY --from=build /app/client/build/libs/client-0.0.1-SNAPSHOT.jar /app/client.jar
CMD [ "java", "-jar", "client.jar" ]