#syntax=docker/dockerfile:1

FROM debian as graalvm
ARG GRAALVM_JAVA_VERSION=22.3.1.r17-grl
SHELL ["/bin/bash", "-c"]
# For SDKMAN to work we need unzip & zip
RUN apt update -y && apt install unzip zip curl build-essential libz-dev zlib1g-dev -y
RUN \
    # Install SDKMAN
    curl -sk "https://get.sdkman.io" | bash  ; \
    source $HOME/.sdkman/bin/sdkman-init.sh ; \
    sdk install java $GRAALVM_JAVA_VERSION ; \
    sdk install gradle ; \
    # Install GraalVM Native Image
    gu install native-image ; \
    gradle --version ; \
    native-image --version

FROM graalvm as build
ARG REPLACE_PROFILE_FILE
SHELL ["/bin/bash", "-c"]

ADD . /build
WORKDIR /build
# Temporary fix
RUN if [[ ! -z "$REPLACE_PROFILE_FILE" ]]; then echo "Replacing profile file"; cp client/src/main/resources/application-$REPLACE_PROFILE_FILE.yml client/src/main/resources/application.yml ; fi
RUN source $HOME/.sdkman/bin/sdkman-init.sh && bash compile-native-client.sh

# We use a Docker multi-stage build here in order to only take the compiled native Spring Boot App from the first build container
FROM debian:stable-slim as runtime
ENV PORT=9090
# Add Spring Boot Native app spring-boot-graal to Container
COPY --from=build "/build/client/build/native/client" client
# Fire up our Spring Boot Native app by default
CMD [ "sh", "-c", "./client -Dserver.port=$PORT" ]