version: '3.8'
services:
  client:
    build:
      context: client
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
    networks:
      - spring-cloud-network
  server:
    build:
      context: server
      dockerfile: Dockerfile
    ports:
      - "9191:9191"
    networks:
      - spring-cloud-network
networks:
  spring-cloud-network:
    driver: bridge