version: '3.8'
services:
  client:
    build:
      context: .
      dockerfile: client/Dockerfile-jar
    ports:
      - "9090:9090"
    environment:
      - CLIENT_HOST=server
      - JAEGER_HOST=jaeger
    networks:
      - spring-cloud-network
  server:
    build:
      context: .
      dockerfile: server/Dockerfile-jar
    ports:
      - "9191:9191"
    environment:
      - JAEGER_HOST=jaeger
    networks:
      - spring-cloud-network
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "9411:9411"
    networks:
      - spring-cloud-network
networks:
  spring-cloud-network:
    driver: bridge