management:
  endpoints:
    web:
      exposure:
        include: httptrace
logging:
  level:
    org:
      springframework:
        web:
          filter:
            CommonsRequestLoggingFilter: DEBUG
server:
  compression:
    enabled: 'true'
  port: '9191'
opentracing:
  jaeger:
    service-name: server
    enabled: true
    udp-sender:
      host: ${JAEGER_HOST:localhost}
