FROM gradle:7-jdk11-focal as build
WORKDIR /app
COPY . .
RUN gradle :server:build

FROM eclipse-temurin:11-jdk-focal as run
WORKDIR /app
COPY --from=build /app/server/build/libs/server-0.0.1-SNAPSHOT.jar /app/server.jar
CMD [ "java", "-jar", "server.jar" ]