management:
  endpoints:
    web:
      exposure:
        include: health,httptrace
feign:
  client:
    config:
      person-client:
        loggerLevel: headers
  compression:
    request:
      enabled: 'true'
      min-request-size: '2048'
      mime-types: text/xml,application/xml,application/json
    response:
      enabled: 'true'
person:
  client:
    url: http://localhost:9191/api
opentracing:
  jaeger:
    service-name: client
    enabled: true
    udp-sender:
      host: ${JAEGER_HOST:localhost}
server:
  port: '9090'
logging:
  level:
    com:
      example:
        demo:
          client: DEBUG

