management:
  endpoints:
    web:
      exposure:
        include: health,httptrace
feign:
  client:
    config:
      person-client:
        loggerLevel: headers
  compression:
    request:
      enabled: 'true'
      min-request-size: '2048'
      mime-types: text/xml,application/xml,application/json
    response:
      enabled: 'true'
person:
  client:
    host: http://server:9191
opentracing:
  jaeger:
    service-name: client
    enabled: true
    udp-sender:
      host: jaeger
server:
  port: '9090'
logging:
  level:
    com:
      example:
        demo:
          client: DEBUG
    org:
      springframework:
        cache: trace

spring:
  main:
    allow-bean-definition-overriding: true

  cloud:
    config:
      enabled: false